name: Linux

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/linux.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libgl1-mesa-dev libmpv-dev

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Set release path
      if: github.event_name == 'release' && github.event.action == 'published'
      run: |
        echo "PROJECT_RELEASE_PATH=${{ github.event.repository.name }}_v${{ github.event.release.tag_name }}_linux_x64" >> $GITHUB_ENV

    - name: Set release path (non-release)
      if: github.event_name != 'release'
      run: |
        echo "PROJECT_RELEASE_PATH=${{ github.event.repository.name }}_dev_linux_x64" >> $GITHUB_ENV

    - name: Copy Artifacts
      run: |
        mkdir -p ${{ env.PROJECT_RELEASE_PATH }}
        cp build/sub-racer/sub-racer ${{ env.PROJECT_RELEASE_PATH }}/
        cp -r build/sub-racer/resources ${{ env.PROJECT_RELEASE_PATH }}/
        cp README.md ${{ env.PROJECT_RELEASE_PATH }}/
        cp LICENSE ${{ env.PROJECT_RELEASE_PATH }}/

    - name: Package
      run: |
        cd ${{ env.PROJECT_RELEASE_PATH }}
        zip -r ../${{ env.PROJECT_RELEASE_PATH }}.zip .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
