name: macOS

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/macos.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest

    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_RELEASE_PATH: ${{ env.PROJECT_NAME }}_dev_macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake mpv

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Setup Release Paths
      run: |
        mkdir -p ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_NAME }}.app/Contents/MacOS
        mkdir -p ${{ env.PROJECT_RELEASE_PATH }}/${{ env.PROJECT_NAME }}.app/Contents/Resources
      if: github.event_name == 'release' && github.event.action == 'published'

    - name: Create .app bundle
      run: |
        mkdir -p ${{ env.PROJECT_NAME }}.app/Contents/MacOS
        mkdir -p ${{ env.PROJECT_NAME }}.app/Contents/Resources
        cp build/sub-racer/sub-racer ${{ env.PROJECT_NAME }}.app/Contents/MacOS/
        cp -r build/sub-racer/resources ${{ env.PROJECT_NAME }}.app/Contents/
        cp README.md ${{ env.PROJECT_NAME }}/
        cp LICENSE ${{ env.PROJECT_NAME }}/

    - name: Package
      run: |
        zip -r ${{ env.PROJECT_RELEASE_PATH }}.zip ${{ env.PROJECT_NAME }}.app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
