name: macOS

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/macos.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install cmake mpv

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Set release path
      if: github.event_name == 'release' && github.event.action == 'published'
      run: |
        echo "PROJECT_RELEASE_PATH=${{ github.event.repository.name }}_v${{ github.event.release.tag_name }}_macos" >> $GITHUB_ENV

    - name: Set release path (non-release)
      if: github.event_name != 'release'
      run: |
        echo "PROJECT_RELEASE_PATH=${{ github.event.repository.name }}_dev_macos" >> $GITHUB_ENV

    - name: Create .app bundle
      run: |
        mkdir -p ${{ github.event.repository.name }}.app/Contents/MacOS
        mkdir -p ${{ github.event.repository.name }}.app/Contents/Resources
        cp build/sub-racer/sub-racer ${{ github.event.repository.name }}.app/Contents/MacOS/
        cp -r build/sub-racer/resources ${{ github.event.repository.name }}.app/Contents/
        cp README.md ${{ github.event.repository.name }}/
        cp LICENSE ${{ github.event.repository.name }}/

    - name: Package
      run: |
        zip -r ${{ env.PROJECT_RELEASE_PATH }}.zip ${{ github.event.repository.name }}.app

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
