name: Windows

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - 'CMakeLists.txt'
      - '.github/workflows/windows.yml'
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: >-
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-libmpv

    - name: Configure CMake
      run: |
        cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Set release path
      if: github.event_name == 'release' && github.event.action == 'published'
      run: |
        echo "PROJECT_RELEASE_PATH=${{ github.event.repository.name }}_v${{ github.event.release.tag_name }}_win_x64" >> $GITHUB_ENV
      shell: bash

    - name: Set release path (non-release)
      if: github.event_name != 'release'
      run: |
        echo "PROJECT_RELEASE_PATH=${{ github.event.repository.name }}_dev_win_x64" >> $GITHUB_ENV
      shell: bash

    - name: Copy Artifacts
      run: |
        mkdir -p ${{ env.PROJECT_RELEASE_PATH }}
        cp build/sub-racer/sub-racer.exe ${{ env.PROJECT_RELEASE_PATH }}/
        cp -r build/sub-racer/resources ${{ env.PROJECT_RELEASE_PATH }}/
        cp README.md ${{ env.PROJECT_RELEASE_PATH }}/
        cp LICENSE ${{ env.PROJECT_RELEASE_PATH }}/
      shell: bash

    - name: Package
      run: |
        cd ${{ env.PROJECT_RELEASE_PATH }}
        7z a -tzip ../${{ env.PROJECT_RELEASE_PATH }}.zip .
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PROJECT_RELEASE_PATH }}.zip
        path: ./${{ env.PROJECT_RELEASE_PATH }}.zip

    - name: Upload Artifact to Release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PROJECT_RELEASE_PATH }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'release' && github.event.action == 'published'
